---
secrets_sops_version: "3.13.3"
secrets_sops_install_path: /usr/local/bin/sops
secrets_age_key_source: ""
secrets_age_key_destination: /etc/platform/keys/age.key

secrets_sops_architectures:
    x86_64: amd64
    aarch64: arm64

secrets_sops_checksums:
    amd64: e5bec3346a873ae91d871550f3e698c1aad962aff462a080e40f25fde17fef6b
    arm64: 53b0abacd38ef1b12a66d6c100956691b9cefce018d91f81e73ddf7438b94d77
